package main

/*
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

import "fmt"

func main() {

	prev1 := 1
	prev2 := 2
	cur := prev1 + prev2

	sum := 2

	for cur < 4000000 {
		if cur%2 == 0 {
			sum += cur
		}

		//compute next
		cur = prev1 + prev2
		prev1 = prev2
		prev2 = cur
	}

	fmt.Println(sum)
}
